### ISSUE TITLE
beef installation not working

### ISSUE THREAD

**Issue by Oneroustorm997** [beefproject/beef#2360] opened 2022-03-16 10:05 UTC
So I executed the ./install command and I'm met with this error is there a solution

![image](https://user-images.githubusercontent.com/73850619/158565903-ab60045f-4707-43d4-9cf3-dd2f98510bea.png)

**Comment by bcoles** [comment] 2022-03-16 10:29
This is an issue with your system packages.

Given that you're using Kali, most of what you need is already installed.

You can probably just do:

```
cd /path/to/beef
gem install bundler
bundle install
``

**Comment by chuckcarne** [comment] 2022-03-21 16:54
when ever I get do ./beef

Could not find eventmachine-1.2.7, thin-1.8.1, sinatra-2.2.0, rack-2.2.3, rack-protection-2.2.0, em-websocket-0.5.3, uglifier-4.2.0, mime-types-3.4.1, execjs-2.8.1, ansi-1.5.0, term-ansicolor-1.7.1, rubyzip-2.3.2, espeak-ruby-1.0.5, otr-activerecord-2.1.1, sqlite3-1.4.2, rubocop-1.26.0, maxmind-db-1.1.1, parseconfig-1.1.2, erubis-2.7.0, msfrpc-client-1.1.2, xmlrpc-0.3.2, rushover-0.3.0, slack-notifier-2.4.0, twitter-7.0.0, async-dns-1.3.0, qr4r-0.6.1, daemons-1.4.1, mustermann-1.1.1, tilt-2.0.10, http_parser.rb-0.6.0, mime-types-data-3.2021.1115, tins-1.29.1, activerecord-7.0.2.2, hashie-forbidden_attributes-0.1.1, parallel-1.21.0, parser-3.1.1.0, rainbow-3.1.1, regexp_parser-2.2.1, rubocop-ast-1.16.0, ruby-progressbar-1.11.0, unicode-display_width-2.1.0, msgpack-1.4.2, webrick-1.7.0, rest-client-2.1.0, addressable-2.8.0, buftok-0.2.0, equalizer-0.0.11, http-4.4.1, http-form_data-2.3.0, memoizable-0.4.2, multipart-post-2.1.1, naught-1.1.0, simple_oauth-0.3.1, async-io-1.32.2, mojo_magick-0.6.6, rqrcode_core-0.2.0, sync-0.5.0, activemodel-7.0.2.2, activesupport-7.0.2.2, hashie-5.0.0, ast-2.4.2, http-accept-1.7.0, http-cookie-1.0.4, netrc-0.11.0, public_suffix-4.0.6, http-parser-1.2.3, thread_safe-0.3.6, async-1.30.1, concurrent-ruby-1.1.9, i18n-1.10.0, tzinfo-2.0.4, domain_name-0.5.20190701, ffi-compiler-1.0.1, console-1.13.1, nio4r-2.5.8, timers-4.3.3, unf-0.1.4, ffi-1.15.4, fiber-local-1.0.0, unf_ext-0.0.7.7 in any of the sources
Run `bundle install` to install missing gems.

I have done bundle install but im not sure how to get all of them at once can some one please help? thanks

**Comment by bcoles** [comment] 2022-03-21 18:52
> I have done bundle install but im not sure how to get all of them at once can some one please help? thanks

That's what `bundle install` does. What makes you think it didn't "get all of them at once" ? And also what does "get all of them at once" mean?

**Comment by chuckcarne** [comment] 2022-03-21 19:54
I think those are dependencies on what beef needs in order to work but for
some reason bundle install does not work. I did a bundle install and it
gives me the same error and tells me to do a bundle install again.

**Comment by bcoles** [comment] 2022-03-21 19:59
Impressive that it did not load a single gem.

There's not really enough information here to reproduce the issue or know the root cause.

Do you have multiple versions of Ruby installed?

You could try running the and see if you get a different error:

```
bundle exec ./beef
```

Alternatively, you could try `rm Gemfile.lock` and run `bundle install` again. But that probably won't work.

A lot more information is required to understand what's going on. Presumably there's an issue with your ruby environment.

**Comment by chuckcarne** [comment] 2022-03-21 22:45
So It now works but it's refusing to hook a browser on my VM. It's giving
me the error sight that can't be reached.

**Comment by bcoles** [comment] 2022-03-21 22:54
> So It now works but it's refusing to hook a browser on my VM. It's giving me the error sight that can't be reached.

A lot more information is required. It is most likely a networking issue. Make sure you can route traffic between whichever host you're running the browser on and the host running BeEF.

**Comment by bcoles** [comment] 2022-03-21 22:55
Closing this issue as the original issue is related to package signing keys used for Kali packages. This is outside the scope of the BeEF project.

**Comment by chuckcarne** [comment] 2022-03-21 22:57
I'm using a cloud warp vpn. Could that be an issue?

**Comment by bcoles** [comment] 2022-03-21 23:07
> I'm using a cloud warp vpn. Could that be an issue?

Maybe. This is a network routing issue. Check your routes.

**Comment by chuckcarne** [comment] 2022-03-21 23:10
how do I do that? I'm pretty new to linux....😬

**Comment by bcoles** [comment] 2022-03-21 23:15
> how do I do that? I'm pretty new to linux....

There is not enough information to know what you're trying to do.

BeEF is a network service like any other. Basic knowledge of networking fundamentals are required. In order to establish a network connection to a network service you must have network route.

**Comment by chuckcarne** [comment] 2022-03-21 23:17
What information do you need?

**Comment by bcoles** [comment] 2022-03-21 23:20
> What information do you need?

Basic network routing questions have been asked many times. SEe

**Closed by bcoles** 2022-03-21 23:20 UTC

**Comment by bcoles** [comment] 2022-03-21 23:25
Edited previous post. Accidentally hit submit prematurely.
