### ISSUE TITLE
Only beef logo if launched on server

### ISSUE THREAD

**Issue by Tonych96** [beefproject/beef#2357] opened 2022-03-15 21:30 UTC
Hello guys,

I am trying to launch a beef on online server. I used ubuntu beef on  linode server and digital ocean ubuntu. Updated all repositories and installed upgrades, connected to ubuntu via ssh, and in browser I see only beef logo and no login and password fields. 

Running Kali on vmware, tried to open the link on host windows, same issue.

launched beef on local server, and it work perfectly locally. 

using the latest Kali on vmware.

**Comment by bcoles** [comment] 2022-03-15 21:34
This usually occurs when the admin UI JavaScript generation fails. This is usually caused by either permission issues (failure to write the combined JS to disk) or when minification fails (nodejs failure)

Are there any errors in the browser console?

Are there are any errors in the terminal where you're running BeEF?

Is nodejs installed and in `$PATH` ?

**Comment by Xcalibur3** [comment] 2022-03-15 22:06
Same problem
![Uploading Screenshot_20220315-230622.png…]()

**Comment by Xcalibur3** [comment] 2022-03-15 22:07
![Screenshot_20220315-230622](https://user-images.githubusercontent.com/101503835/158480457-c40a86a0-48b1-4744-944f-77f513119492.png)

**Comment by bcoles** [comment] 2022-03-15 22:12
> Same problem

This usually occurs when the admin UI JavaScript generation fails. This is usually caused by either permission issues (failure to write the combined JS to disk) or when minification fails (nodejs failure)

Are there any errors in the browser console?

Are there are any errors in the terminal where you're running BeEF?

Is nodejs installed and in `$PATH` ?

**Comment by Xcalibur3** [comment] 2022-03-15 22:14
There is no error on beef and termux and i can access storage

The path is storage no?

**Comment by Xcalibur3** [comment] 2022-03-15 22:16
![Screenshot_20220315-231506](https://user-images.githubusercontent.com/101503835/158481436-4407cfca-a7c2-4304-9063-924b9cc20103.png)

**Comment by bcoles** [comment] 2022-03-15 22:17
> There is no error on beef and termux and i can access storage
> 
> The path is storage no?

No idea. BeEF was never intended to be run in Termux and none of the developers have tested on Termux.

However, a few people have had success running BeEF on Termux.

BeEF bundles several JavaScript files together and writes these to disk upon startup. The user running BeEF must have write permission to the `extensions/admin_ui/media/javascript-min/` directory.

**Comment by DeezyE** [comment] 2022-03-15 23:43
Agree with bcoles, we've not tested in Termux.
I have not personally vetted this, but here's a post on beef in termux:
https://www.onlinehacking.in/how-to-install-beef-framework-in-termux-linux

Please let us know if this helps

**Comment by przemek1230987** [comment] 2022-03-16 00:17
Same problem, also running on linode

**Comment by bcoles** [comment] 2022-03-16 00:19
> Same problem, also running on linode

This usually occurs when the admin UI JavaScript generation fails. This is usually caused by either permission issues (failure to write the combined JS to disk) or when minification fails (nodejs failure)

Are there any errors in the browser console?

Are there are any errors in the terminal where you're running BeEF?

Is nodejs installed and in `$PATH` ?

**Comment by bcoles** [comment] 2022-03-16 00:32
This is a bug. Patch incoming shortly.

**Comment by bcoles** [comment] 2022-03-16 00:36
Thanks. This has been fixed. The patch should be available once you `git pull`.

**Comment by przemek1230987** [comment] 2022-03-16 00:37
> > Same problem, also running on linode
> 
> This usually occurs when the admin UI JavaScript generation fails. This is usually caused by either permission issues (failure to write the combined JS to disk) or when minification fails (nodejs failure)
> 
> Are there any errors in the browser console?
> 
> Are there are any errors in the terminal where you're running BeEF?
> 
> Is nodejs installed and in `$PATH` ?

No errors anywhere.

**Comment by Tonych96** [comment] 2022-03-16 08:36
Thank you @bcoles , it is working now! Appreciate!

**Comment by bcoles** [comment] 2022-03-16 08:40
> Thank you @bcoles , it is working now! Appreciate!

Cool. Closing this issue.

The bug was introduced 3 days ago and is now patched. If anyone encounters this issue, ensure you're using the latest version of BeEF. If the bug is still present on the latest version, see https://github.com/beefproject/beef/issues/2357#issuecomment-1068594559 for troubleshooting info.

**Closed by bcoles** 2022-03-16 08:40 UTC
Labels: Defect
