### ISSUE TITLE
Man-in-the-browser attack on IE is broken when using Proxy

### ISSUE THREAD

**Issue by jamescrowley** [beefproject/beef#1018] opened 2014-05-14 22:25 UTC
If you apply the man-in-the-browser attack on IE 11 (not sure about earlier versions), and then attempt to use the hooked browser to proxy the requests, the man-in-the-browser hook is broken, as IE redirects the whole page to the one requested by the proxy...

**Comment by bcoles** [comment] 2017-04-16 14:00
I'm not sure what the issue is here. A large number of changes have been made to the Requester and Proxy since this issue was created. This issue may or may not be resolved.

The Man-in-the-Browser module never worked on IE. The code was never designed for IE and to the best of my knowledge the attack never worked in IE. However, I can't find the original blog post.

Closing this issue.

**Closed by bcoles** 2017-04-16 14:00 UTC
Labels: Defect, Priority Review
