### ISSUE TITLE
Error with extract inotes command

### ISSUE THREAD

**Issue by mavthedev** [beefproject/beef#2364] opened 2022-03-18 17:29 UTC
I ran the extract inotes command once and now every instance I run instantly crashes and tries over and over to reinitialize but doesn't work and I get this error every second
[error.txt](https://github.com/beefproject/beef/files/8306518/error.txt)

The logs end before the error starts.
This is the last thing in the logs:
[beef.log](https://github.com/beefproject/beef/files/8306520/beef.log)
Client-side logs are just full of 500 internal server errors.

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:** 0.5.4.0

2. **Ruby Version:** ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin21]
3. **Browser Details (e.g. Chrome v81.0):** Chrome: v99.0.4844.51 (Official Build) (x86_64)

4. **Operating System (e.g. OSX Catalina):** OSX Montery v12.2.1 (21D62)
 

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** None, except username and password change

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** Nope

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
for BeEF to run normally and let me hack myself
<br />
**Actual Behaviour:**
It crashes instantly and tries to restart but instead gets the same error
<br />

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1. Use the butcher demo to create an instance.
2. **TRY** to use the extract iNotes command

**Comment by bcoles** [comment] 2022-03-18 22:02
Thanks for the report.

This module has not been updated since it was added in 2014.

* https://github.com/beefproject/beef/commits/master/modules/misc/ibm_inotes/extract_inotes_list

It contains a very obvious typo:

```diff
diff --git a/modules/misc/ibm_inotes/extract_inotes_list/command.js b/modules/misc/ibm_inotes/extract_inotes_list/command.js
index 72e3dd35..ddc87344 100644
--- a/modules/misc/ibm_inotes/extract_inotes_list/command.js
+++ b/modules/misc/ibm_inotes/extract_inotes_list/command.js
@@ -15,7 +15,7 @@
 //
 beef.execute(function() {
        var startdate = '<%= @startdate %>';
-       var enddate = '<%= @endddate %>';
+       var enddate = '<%= @enddate %>';
        var count = '<%= @count %>';
        
        //get URL for this nsf databse
```

Sadly, resolving the typo is insufficient to resolve this issue. This issue also seems to affect other iNotes related modules, such as `Read iNotes`.

I get a different stack trace but the root cause is likely the same.

```
2022-03-18 17:31:17 - NameError - `@' is not allowed as an instance variable name:
	/usr/lib/ruby/vendor_ruby/erubis/context.rb:44:in `instance_variable_set'
	/usr/lib/ruby/vendor_ruby/erubis/context.rb:44:in `[]='
	/root/Desktop/beef/core/main/command.rb:192:in `block in output'
	/root/Desktop/beef/core/main/command.rb:191:in `each'
	/root/Desktop/beef/core/main/command.rb:191:in `output'
	/root/Desktop/beef/core/main/handlers/modules/command.rb:68:in `add_command_instructions'
	/root/Desktop/beef/core/main/handlers/hookedbrowsers.rb:97:in `block (2 levels) in <class:HookedBrowsers>'
	/var/lib/gems/2.7.0/gems/activerecord-7.0.2.2/lib/active_record/relation/delegation.rb:88:in `each'
	/var/lib/gems/2.7.0/gems/activerecord-7.0.2.2/lib/active_record/relation/delegation.rb:88:in `each'
	/root/Desktop/beef/core/main/handlers/hookedbrowsers.rb:97:in `block in <class:HookedBrowsers>'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
	/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
```

This issue is caused by module options which do not have a `name` property. The following diff resolves the issue.

```diff
diff --git a/modules/misc/ibm_inotes/extract_inotes_list/command.js b/modules/misc/ibm_inotes/extract_inotes_list/command.js
index 72e3dd35..ddc87344 100644
--- a/modules/misc/ibm_inotes/extract_inotes_list/command.js
+++ b/modules/misc/ibm_inotes/extract_inotes_list/command.js
@@ -15,7 +15,7 @@
 //
 beef.execute(function() {
 	var startdate = '<%= @startdate %>';
-	var enddate = '<%= @endddate %>';
+	var enddate = '<%= @enddate %>';
 	var count = '<%= @count %>';
 	
 	//get URL for this nsf databse
diff --git a/modules/misc/ibm_inotes/extract_inotes_list/module.rb b/modules/misc/ibm_inotes/extract_inotes_list/module.rb
index 7c8b25ee..ba385f31 100644
--- a/modules/misc/ibm_inotes/extract_inotes_list/module.rb
+++ b/modules/misc/ibm_inotes/extract_inotes_list/module.rb
@@ -16,7 +16,7 @@
 class Extract_inotes_list < BeEF::Core::Command
   def self.options
     [
-      { 'type' => 'label', 'html' => 'Provide date boundaries to retrieve a list of Notes:' },
+      { 'type' => 'label', 'name' => 'asdf', 'html' => 'Provide date boundaries to retrieve a list of Notes:' },
       { 'type' => 'textfield', 'name' => 'startdate', 'ui_label' => 'startdate yyyymmdd', 'value' => '20140101' },
       { 'type' => 'textfield', 'name' => 'enddate', 'ui_label' => 'enddate yyyymmdd', 'value' => '20500101' },
       { 'type' => 'textfield', 'name' => 'count', 'ui_label' => 'number of items returned', 'value' => '-1' }
diff --git a/modules/misc/ibm_inotes/inotes_flooder/module.rb b/modules/misc/ibm_inotes/inotes_flooder/module.rb
index 48758946..735754a9 100644
--- a/modules/misc/ibm_inotes/inotes_flooder/module.rb
+++ b/modules/misc/ibm_inotes/inotes_flooder/module.rb
@@ -16,7 +16,7 @@
 class Inotes_flooder < BeEF::Core::Command
   def self.options
     [
-      { 'type' => 'label', 'html' => 'Send a note to someone with an attachment:' },
+      { 'type' => 'label', 'name' => 'asdf', 'html' => 'Send a note to someone with an attachment:' },
       { 'type' => 'textfield', 'name' => 'to', 'ui_label' => 'TO', 'value' => '' },
       { 'type' => 'textfield', 'name' => 'subject', 'ui_label' => 'Subject', 'value' => '' },
       { 'name' => 'body', 'ui_label' => 'Body', 'type' => 'textarea', 'value' => '' },
diff --git a/modules/misc/ibm_inotes/read_inotes/module.rb b/modules/misc/ibm_inotes/read_inotes/module.rb
index b0b12d67..ecb4ba2b 100644
--- a/modules/misc/ibm_inotes/read_inotes/module.rb
+++ b/modules/misc/ibm_inotes/read_inotes/module.rb
@@ -16,7 +16,7 @@
 class Read_inotes < BeEF::Core::Command
   def self.options
     [
-      { 'type' => 'label', 'html' => 'Provide unid to retrieve details of a Note:' },
+      { 'type' => 'label', 'name' => 'asdf', 'html' => 'Provide unid to retrieve details of a Note:' },
       { 'type' => 'textfield', 'name' => 'unid', 'ui_label' => 'notes unid', 'value' => '1' }
     ]
   end
diff --git a/modules/misc/ibm_inotes/send_inotes/module.rb b/modules/misc/ibm_inotes/send_inotes/module.rb
index d8d6dd19..18842588 100644
--- a/modules/misc/ibm_inotes/send_inotes/module.rb
+++ b/modules/misc/ibm_inotes/send_inotes/module.rb
@@ -16,7 +16,7 @@
 class Send_inotes < BeEF::Core::Command
   def self.options
     [
-      { 'type' => 'label', 'html' => 'Send a note to someone:' },
+      { 'type' => 'label', 'name' => 'asdf', 'html' => 'Send a note to someone:' },
       { 'type' => 'textfield', 'name' => 'to', 'ui_label' => 'TO:', 'value' => '' },
       { 'type' => 'textfield', 'name' => 'subject', 'ui_label' => 'Subject:', 'value' => '' },
       { 'name' => 'body', 'ui_label' => 'Body', 'type' => 'textarea', 'value' => '' }
diff --git a/modules/misc/ibm_inotes/send_inotes_with_attachment/module.rb b/modules/misc/ibm_inotes/send_inotes_with_attachment/module.rb
index 564db0b9..09f5b2c4 100644
--- a/modules/misc/ibm_inotes/send_inotes_with_attachment/module.rb
+++ b/modules/misc/ibm_inotes/send_inotes_with_attachment/module.rb
@@ -16,7 +16,7 @@
 class Send_inotes_with_attachment < BeEF::Core::Command
   def self.options
     [
-      { 'type' => 'label', 'html' => 'Send a note to someone with an attachment:' },
+      { 'type' => 'label', 'name' => 'asdf', 'html' => 'Send a note to someone with an attachment:' },
       { 'type' => 'textfield', 'name' => 'to', 'ui_label' => 'TO', 'value' => '' },
       { 'type' => 'textfield', 'name' => 'subject', 'ui_label' => 'Subject', 'value' => '' },
       { 'name' => 'body', 'ui_label' => 'Body', 'type' => 'textarea', 'value' => '' },

```

Also, the `arr` regex in each of these modules causes JavaScript errors.

```
execute_commands - command failed to execute: arr is null
```

We should also have some tests and validation at startup to ensure other modules do not cause the same issue.

**Comment by DeezyE** [comment] 2022-03-23 01:19
Looks like all these inotes modules have no handling for a lack of nsf data (arr null) across the board

**Closed** 2022-07-28 07:13 UTC
Labels: Defect, Module
