### ISSUE TITLE
Autorun Rule Error

### ISSUE THREAD

**Issue by seeblog** [beefproject/beef#2103] opened 2021-05-11 13:05 UTC
Linux instance-20210415-1612 5.4.0-1043 #46-Ubuntu SMP Tue Apr 13 09:12:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

root@ubuntu-1612:~/beef# ls arerules/enabled/
README  confirm_close_tab.json  man_in_the_browser.json

The first hooked browser can run normally
Prompt when running again after finishing the process: 
[!] [WebSocket] Error: SQLite3::ConstraintException: UNIQUE constraint failed: executions.id

details:

[12:38:43][*] [ARE] Ruleset (Perform Man-In-The-Browser) parsed and stored successfully.
[12:38:43][*] [ARE] Ruleset (Confirm Close Tab) parsed and stored successfully.
[12:38:43][*] Starting WebSocket server ws://0.0.0.0:61985 [timer: 5000]
[12:38:43][*] Starting WebSocketSecure server on wss://[0.0.0.0:61986 [timer: 5000]
[12:38:43][*] BeEF server started (press control+c to stop)
[12:52:40][*] [ARE] Checking if any defined rules should be triggered on target.
[12:52:40]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:40]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:40]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[12:52:40]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:40]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:40]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[12:52:40]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:40]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:40]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[12:52:40]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:40]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:40]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[12:52:40]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:40]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:40]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[12:52:40]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:40]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:40]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[12:52:40]    |_  Found [6/6] ARE rules matching the hooked browser type/version.
[12:52:40]    |_  Preparing JS for command id [11], module [man_in_the_browser]
[12:52:40][!] [WebSocket] Error: SQLite3::ConstraintException: UNIQUE constraint failed: executions.id
[12:52:46][*] [ARE] Checking if any defined rules should be triggered on target.
[12:52:46]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:46]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:46]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[12:52:46]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:46]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:46]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[12:52:46]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:46]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:46]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[12:52:46]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:46]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:46]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[12:52:46]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:46]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:46]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[12:52:46]    |_  Browser version check -> (hook)  ALL (rule) : true
[12:52:46]    |_  OS version check -> (hook) 7 ALL (rule): true
[12:52:46]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[12:52:46]    |_  Found [6/6] ARE rules matching the hooked browser type/version.
[12:52:46]    |_  Preparing JS for command id [12], module [man_in_the_browser]
[12:52:46][!] [WebSocket] Error: SQLite3::ConstraintException: UNIQUE constraint failed: executions.id

How can I resolve this error, thanks!

**Comment by DeezyE** [comment] 2022-03-17 00:27
@seeblog can you provide more context to your issue?

**Comment by bcoles** [comment] 2022-03-17 00:28
This is likely a duplicate of #1968 which was never resolved.

**Closed** 2023-04-01 16:05 UTC
Labels: Defect, Autorun Rules Engine
