### ISSUE TITLE
Could not find table 'webcloners' and Invalid JSON input passed to endpoint /api/seng/clone_page

### ISSUE THREAD

**Issue by fa1c0n1** [beefproject/beef#2010] opened 2020-11-07 05:34 UTC
When I clone a website by BeEF, it alerts an error as screenshot shown as below.
How to solve this problem？？
`curl -H "Content-Type: application/json; charset=UTF-8" -d '{"url":"https://www.baidu.com", "mount":"/baidu"}' -X POST 'http://192.168.166.176:3000/api/seng/clone_page?token=912e3124ee5057b76ce1144b2e14d4aa9e8a2499'`
![image](https://user-images.githubusercontent.com/11158624/98432915-8aa7ce80-20fd-11eb-8160-2962ea7ddef2.png)

**Comment by andyita** [comment] 2021-01-16 14:32
I'm having the same "Invalid JSON input passed to endpoint /api/seng/clone_page" error. Any idea on how to solve?

**Comment by york-cmd** [comment] 2021-01-16 18:05
I'm having the same "Invalid JSON input passed to endpoint /api/seng/clone_page" error. Any idea on how to solve?

**Comment by violentr** [comment] 2021-03-26 18:48
Same issue here, Invalid JSON  input passed to endpoint `/api/seng/clone_page`
```
curl -H "Content-Type: application/json; charset=UTF-8" \
-X POST http://127.0.0.1:3000/api/seng/clone_page?token=$beef_rest_api_token \
-d '{"url":"https://somesite.com","mount":"/somesite"}'
```

**Comment by wheatley** [comment] 2021-06-25 04:46
hi @fa1c0n1, @violentr & @andyita 
was able to replicate your issues and look into the root cause of what was happening.

it looks likes the logic around persistence is erroring out.
I've gone and found the code that is throwing the error and have produced a solution.
I'll raise a pull request and look into resolving this for you.

**Comment by ma1ware07** [comment] 2021-07-05 12:11
Any updates on this? Been encountering this issue as well.

**Comment by wheatley** [comment] 2021-07-05 23:36
hey ma1ware07, will have this resolved by the end of the week and update this issue for everyone

**Comment by wheatley** [comment] 2021-07-10 23:54
just letting everyone know that's watching this issue, just finishing up some tests and will be creating a pull request

**Comment by wheatley** [comment] 2021-07-11 08:34
@ma1ware07 pull request has been request to address this issue.

**Closed** 2021-07-13 11:49 UTC
Labels: Defect, Maintainability, Priority High
