### ISSUE TITLE
hook.js probably dont work(demo not for me)

### ISSUE THREAD

**Issue by Sa1tama228** [beefproject/beef#3008] opened 2024-01-17 12:03 UTC
Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
BeEF Version:latest
Ruby Version:latest
Browser Details (e.g. Chrome v81.0): testing at opera and chrome
Operating System (e.g. OSX Catalina):kali and windows 10
Configuration
Have you made any changes to your BeEF configuration? No
Have you enabled or disabled any BeEF extensions? No
Steps to Reproduce

https://imgur.com/a/R1GBq3Z 
![Screenshot_821](https://github.com/beefproject/beef/assets/104623364/268c5039-5d91-407f-a17d-80c22ffd952a)
(and browser won't be hooked.Just opens this. and i know about demo, but im need full)

**Comment by Sa1tama228** [comment] 2024-01-17 12:13
re-issue

**Comment by bcoles** [comment] 2024-01-17 12:19
Dupe of #3007.

**Closed by bcoles** 2024-01-17 12:19 UTC
Labels: Question
