### ISSUE TITLE
Bundle install for Beef in Kali

### ISSUE THREAD

**Issue by MaadayKara** [beefproject/beef#3222] opened 2024-11-17 14:51 UTC
I have been trying to install Beef but sqlite3 doesn't allow me to do that. I'm adding screenshot of the problem. Could you help me on this please?
![kali ](https://github.com/user-attachments/assets/8670c2d3-a62a-45b9-a4fe-f070b308e6e1)

**Comment by Aqbmn** [comment] 2024-11-23 11:05
arm64-v8a, armeabi-v7a, armeabi

Supported Locales: af, am, ar, ar-AE, ar-IL, as, as-IN, az, az-AZ, be, be-BY, bg, bg-BG, bn, bn- BD, bn-IN, bs, bs-BA, ca, ca-ES, cs, cs-CZ, da, da-DK, de, de-AT, de-CH, de-DE, el, el-GR, en, en-AU, en-CA, en-DI, en-GB, en-IE, en-NZ, en- PH, en-US, en-ZA, en-ZG, es, es-ES, es-US, et, et-EE, eu, eu-ES, fa, fa-IR, fi, fi-FI, fil, fil-PH, fr, fr- BE, fr-CA, fr-CH, fr-FR, ga, ga-IE, gl, gl-ES, gu, gu-IN, hi, hi-IN, hr, hr-HR, hu, hu-HU, hy, hy-AM, in, in-ID, is, is-IS, it, it-IT, iw, iw-IL, ja, ja-JP, ka, ka-GE, kk, kk-KZ, km, km-KH, kn, kn-IN, ko, ko- KR, ky, ky-KG, lo, lo-LA, It, It-LT, Iv, Iv-LV, mk, mk- MK, ml, ml-IN, mn, mn-MN, mr, mr-IN, ms, ms- MY, my, my-MM, my-ZG, nb, nb-NO, ne, ne-NP, nl, nl-BE, nl-NL, or, or-IN, pa, pa-IN, pl, pl-PL, pl- SP, pt, pt-BR, pt-PT, ro, ro-RO, ru, ru-RU, si, si- LK, sk, sk-SK, sl, sl-SI, sq, sq-AL, sr, sr-Latn, sr- RS, sv, sv-SE, sw, ta, ta-IN, te, te-IN, tg, tg-TJ, th, th-TH, tk, tk-TM, tr, tr-TR, uk, uk-UA, ur, ur- PK, uz, uz-UZ, vi, vi-VN, zh-CN, zh-HK, zh-TW, zu

**Comment by Aqbmn** [comment] 2024-11-23 11:08
`
Duplicate of #`

**Comment by Aqbmn** [comment] 2024-11-23 11:09
![Uploading PXL_20240118_162445855.jpg…]()

**Comment by Aqbmn** [comment] 2024-11-23 11:09
![IMG-20230903-WA0092](https://github.com/user-attachments/assets/7a66e5c5-b072-4d31-99a8-168fdd709272)
![IMG-20230903-WA0097](https://github.com/user-attachments/assets/15c8404b-bdd0-4392-b966-bcbbd8d867f4)
![IMG-20230903-WA0100](https://github.com/user-attachments/assets/ab580689-2010-4fa4-91eb-d61d168cc88f)

**Comment by stephenakq** [comment] 2024-11-24 18:34
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc

**Closed by stephenakq** 2024-11-24 18:34 UTC

**Comment by Aqbmn** [comment] 2024-11-25 23:00
Hmm

**Comment by Aqbmn** [comment] 2024-11-25 23:02
Lisn
