### ISSUE TITLE
Miner is not defined (Crypto Loot Mod)

### ISSUE THREAD

**Issue by crypto-maniac** [beefproject/beef#1702] opened 2019-03-06 20:56 UTC
What version/revision of BeEF are you using?

On what version of Ruby?
2.1

On what browser?

Chrome

On what operating system?

Centos 6

#### Configuration

Are you using a non-default configuration?
No

Have you enabled or disabled any BeEF extensions?

i use the default config

#### Summary

Hello, i try to run the crypto loot command but it return
"data: error=miner is not defined" in the console
i have correctly inserted my key , is there any step to do for run the miner please ?
thanks you very much

#### Expected Behaviour

run the miner

**Comment by bcoles** [comment] 2019-03-08 12:41
The CryptLoot module loads the miner script from:

```
https://crypto-loot.com/lib/miner.min.js
```
The website appears to be down at the moment.

Also, last I checked (years ago), the CryptoLoot web server made use of an untrusted SSL cert.

The JavaScript library is loaded from the CryptoLoot server in the background, so failed SSL connections would be invisible.

Check the browser web developer console. You're probably receiving connection errors or SSL verification errors.

**Comment by crypto-maniac** [comment] 2019-03-08 18:44
hello bcoles, thanks you for your answer

as far i can see they use cloudflare https and their certificate is valid for this dns
https://i.snag.gy/3z5xEO.jpg
also i can see that is it possible to use the library as self hosted files
https://github.com/Crypto-Loot/cryptoloot/archive/master.zip

so in theory there should be a way to run the miner 

isnt' it ? 

thanks you

**Comment by bcoles** [comment] 2019-03-08 19:41
Yes it should be possible to run the miner.

The command module was written ages ago. It's possible that the API has since changed.

**Comment by bcoles** [comment] 2019-03-08 19:46
Confirmed that the module is currently not working.

A valid account is required to access the CryptoLoot documentation. I won't be fixing this module.

If you get it working, please submit a patch pull request.

**Comment by crypto-maniac** [comment] 2019-03-08 21:14
hello , here is the API reference i copied on this pastebin
https://pastebin.com/M9XrncUG

to be honest , i wont be able to fix myself ...

all the best

**Comment by bcoles** [comment] 2023-04-02 11:10
Thanks for providing the documentation. That's useful and the effort is appreciated.

Unfortunately I could not care less about this module. It looks like no one else cares about it either - it has been broken for 4 years.

Also, the `command.js` file was indiscriminately deleted in 7c5578329fb17c5cccbf63b97cbe3c8371d4d72e 3 years ago without explanation. Presumably due to a combination of overzealous anti-virus scanner and uncaring committer.

This module has been removed in #2787. Closing.

**Closed by bcoles** 2023-04-02 11:10 UTC
Labels: Defect, Module, Low
