### ISSUE TITLE
Can't login admin panel

### ISSUE THREAD

**Issue by cool1coder** [beefproject/beef#2553] opened 2022-08-25 08:06 UTC
https://user-images.githubusercontent.com/102613272/186610441-ae10bcc6-6f63-4fb8-9d55-bd44e3fcea85.mp4

<img width="423" alt="image" src="https://user-images.githubusercontent.com/102613272/186610493-72a3aec9-0750-4028-b464-b3869eacb2a4.png">

I can't login i could with the older updates but the new one is having this bug

does anyone know how to fix this?

**Comment by bcoles** [comment] 2022-08-25 10:18
It is not possible to login the admin panel when using ngrok. This is a bug.

You will need to login via one of the network interfaces instead.

**Comment by bcoles** [comment] 2022-08-25 10:19
Dupe of #2553.

**Closed by bcoles** 2022-08-25 10:19 UTC

**Comment by cool1coder** [comment] 2022-08-25 19:38
> It is not possible to login the admin panel when using ngrok. This is a bug.
> 
> You will need to login via one of the network interfaces instead.
