### ISSUE TITLE
Beef not working on 2G/3G/4G devices

### ISSUE THREAD

**Issue by kaos69** [beefproject/beef#1209] opened 2016-02-06 22:53 UTC
Beef is not working in mobile devices which get internet by 2G/3G/4G , it is working perfect in wired and wireless connected browsers.
The funny thing is that I can send modules at the same phone when it's connected by wifi, but not when it's connected with 3G, at the beef demo site.

Also when I release hotspot from that mobile which is connected by 3G but for which beef is not functioning, all other mobiles connected wirelessly to the 3G mobile phone are hooked and I can execute modules against all of them but not at the main device connected by 3G.

Beef is on a public server. 
Any clue ???

**Comment by bcoles** [comment] 2016-02-07 00:47
Hi @kaos69

I've hooked browsers on 3G/4G in the past.

Perhaps your network provider blocks some ports? Or does content filtering?

To test ports, try changing BeEF from port 3000 to 80. Or try enabling HTTPS (on port 443). You'll need a valid cert, though.

Alternatively, try enabling web sockets and using the websocket ports.

To test content filtering, try enabling evasion with `beef.extensions.evasion.enable`

I'm not sure I fully understand what you mean about the hotspot configuration. Do you have access to another network provider to test? Can you try using one of the other mobile devices as a hotspot and see if that works?

**Comment by kaos69** [comment] 2016-02-08 21:58
Currently I'm too busy, but those days I'll try and will come with some new research on this.

Port 80 is already used, and I don't have valid certs for 443, so which other ports would you prefer ?
Also I'm using WebSockets so which port should I try to use for WebSockets and which port for XHR-Polling when WebSockets are not supported ?

Evasion is enabled all the time.

With the Hotspot I mean that beef is not working for device A when it is connected through 3G, but when device A  is connected with Wi-Fi beef is functioning. So when device A is connected through 3G and is set as a Hotspot, another Device B is connected with Wi-Fi to Device A, and the device B is functioning with beef but the Device A itself is not. 

This is kinda funny and I don't have a clue why its like that, if it was a port problem or something how is beef functioning for Device B which gets internet from Device A, but the Device A itself is not.

I'm going to do some more research on this but I would really appreciate if you could suggest me something ?

THANK YOU

**Comment by bcoles** [comment] 2016-02-09 07:18
I'm not sure what's causing this issue. Perhaps it's your network provider. Perhaps it's anti-virus on device A. Perhaps it's something else entirely.

For testing purposes you can use self-signed certs, just make sure you accept the cert warnings in the browser you intend to hook before you browse to the hook page.

The default ports for websockets should be fine.

What page are you hooking with? The `basic.html` demo? Try the `plain.html` demo instead.

Is hook.js loading successfully? If so:

* Is the hooked browser trying to communicate with the BeEF server? (check the Network tab of browser development tools, or use Wireshark, to check for requests to the BeEF server)
* Is BeEF giving any errors in console? What about with `debug: true` set in `config.yaml`?

Try increasing the `xhr_poll_timeout` from 1000 to 30000 (30 seconds).

Do you have access to another 3G network provider to test?

**Comment by antisnatchor** [comment] 2016-02-18 14:55
Are you using an IP or are you serving the hook via a ligitimate site like http://domain-hooked.com ?
No problems here, I've hooked android, blackberry, iOS on 3 and 4g.

**Comment by bcoles** [comment] 2016-04-28 11:24
Closing this issue as unable to reproduce

**Closed by bcoles** 2016-04-28 11:24 UTC
Labels: Priority Low

**Comment by basinas13** [comment] 2018-01-18 20:42
Hi again and sorry I am digging out an old thread but it seems that indeed there is some kind of issue on android phones on 3G/4G network that might, however, not have any relation with BeEF.

I used ngrok to forward the port but after clicking the address on the android phone, I see this in Ngrok:

![hook server error](https://user-images.githubusercontent.com/35409232/35120174-f86e38ee-fc9f-11e7-925f-388005a585da.JPG)

The hook is successful when on Wi-Fi, but not on another network.

**Comment by CalfCrusher** [comment] 2020-04-18 11:31
i have same problem. All portforwarding is set correctly, i just can't hook my smartphone via 3/4g connection, something occurs.  I mean that from mobilephone i can loads for example the /demos/basic.html test page but without hooking it. Very strange
