### ISSUE TITLE
Nested-Forward ARE rules doens't work

### ISSUE THREAD

**Issue by laravelhelp2** [beefproject/beef#1810] opened 2019-12-18 08:30 UTC
#### Environment

What version/revision of BeEF are you using? 0.5.0.0

On what version of Ruby? 2.4.9p362

On what browser? Firefox, Chrome

On what operating system? Linux, Windows

#### Configuration

Are you using a non-default configuration? no

Have you enabled or disabled any BeEF extensions? yes

#### Summary

I created a simple nested-forward are rule. The last one should be trigger when user try to close their hooked tab but nothing happen. I did put  "condition": "status==-1" that means user tried to close their tab (ERROR == -1).

#### Expected Behaviour

The "invisible_iframe" rule should be triggered after user click to close their tab.

#### Actual Behaviour

No second rule is ran.

#### Steps to Reproduce
Sample rule to be put in arerules/enabled

```
{"name": "Confirm Close Tab",
  "author": "mgeeky",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [
    {"name": "confirm_close_tab",
      "condition": null,
      "code": null,
      "options": {
        "text":"Are you sure you want to navigate away from this page?",
        "usePopUnder":"true"
      }
    },
    {
      "name": "invisible_iframe",
      "condition": "status==-1",
      "code": null,
      "options": {
        "target": "http://127.0.0.1:8080/"
      }
    }
  ],
  "execution_order": [0,1],
  "execution_delay": [0,0],
  "chain_mode": "nested-forward"
}
```

#### Additional Information

n/a

**Comment by jcrew99** [comment] 2019-12-18 23:07
@laravelhelp2 In the update to 0.5.0.0 from 0.4.7.3, DataMapper was changed to ActiveRecord. It doesn't seem to support Ruby 2.4.x. Would you be able to update your Ruby version to 2.5 onwards otherwise there is a branch called master-0.4.7.3 that has BeEF before the Active-Record merge. 
This would be the issues if the tables aren't being created, could you please check that is the case.

**Comment by laravelhelp2** [comment] 2019-12-19 12:04
I installed ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu] and got a fresh 0.5.0.0 BeEF package. I did ./install all ok but when I tried to run ./beef I got this exception:

```
Traceback (most recent call last):
	5: from ./beef:44:in `<main>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /tmp/beef-master/core/loader.rb:9:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
```

**Comment by jcrew99** [comment] 2019-12-20 07:27
What is your rubygem version? try updating it. You put Linux, windows as your version, what specific flavours? for example, Windows Sub with kali?

**Comment by laravelhelp2** [comment] 2019-12-20 12:30
I was using the wrong (2.4) rubygem. 
Now I installed all (ruby 2.5.7p206 and gem 3.1.2 on Ubuntu 16.04) and beef starts but I got an infinite loop and ARE rules don't work:

```
...
[12:07:06][!] API Fire Error: Could not find table 'https' in {:owner=>BeEF::Extension::Requester::RegisterPreHookCallback, :id=>18}.pre_hook_send()
[12:07:06][!] API Fire Error: Could not find table 'xssraysscans' in {:owner=>BeEF::Extension::Xssrays::RegisterPreHookCallback, :id=>20}.pre_hook_send()
[12:07:07][!] API Fire Error: Could not find table 'https' in {:owner=>BeEF::Extension::Requester::RegisterPreHookCallback, :id=>18}.pre_hook_send()
[12:07:07][!] API Fire Error: Could not find table 'xssraysscans' in {:owner=>BeEF::Extension::Xssrays::RegisterPreHookCallback, :id=>20}.pre_hook_send()
[12:07:08][!] API Fire Error: Could not find table 'https' in {:owner=>BeEF::Extension::Requester::RegisterPreHookCallback, :id=>18}.pre_hook_send()
[12:07:08][!] API Fire Error: Could not find table 'xssraysscans' in {:owner=>BeEF::Extension::Xssrays::RegisterPreHookCallback, :id=>20}.pre_hook_send()
[12:07:09][!] API Fire Error: Could not find table 'https' in {:owner=>BeEF::Extension::Requester::RegisterPreHookCallback, :id=>18}.pre_hook_send()
[12:07:09][!] API Fire Error: Could not find table 'xssraysscans' in {:owner=>BeEF::Extension::Xssrays::RegisterPreHookCallback, :id=>20}.pre_hook_send()
[12:07:11][!] API Fire Error: Could not find table 'https' in {:owner=>BeEF::Extension::Requester::RegisterPreHookCallback, :id=>18}.pre_hook_send()
[12:07:11][!] API Fire Error: Could not find table 'xssraysscans' in {:owner=>BeEF::Extension::Xssrays::RegisterPreHookCallback, :id=>20}.pre_hook_send()
...
```

Also when I try to delete a zombie from dashboard I'm unable to do that and I got following exception:

```
2019-12-20 12:07:12 - ArgumentError - wrong number of arguments (given 0, expected 1):
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:325:in `destroy'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:65:in `block in destroy'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:398:in `block in scoping'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:773:in `_scoping'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:398:in `scoping'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:65:in `destroy'
	/tmp/beef/core/main/rest/handlers/hookedbrowsers.rb:44:in `block in <class:HookedBrowsers>'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1635:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1006:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1035:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1033:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:985:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:984:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1094:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1071:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:919:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:908:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.7/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.7/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.7/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.7/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.7/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.8/lib/rack/null_logger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.8/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1950:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.0.8/lib/rack/urlmap.rb:68:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-2.0.8/lib/rack/urlmap.rb:53:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.0.8/lib/rack/urlmap.rb:53:in `call'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/tmp/beef/core/main/server.rb:165:in `start'
	./beef:232:in `<main>'
```

**Comment by laravelhelp2** [comment] 2019-12-23 17:42
@jcrew99 I tried also with other ruby versions using RVM but I always got the same exceptions:

..
[17:38:06][!] API Fire Error: Could not find table 'https' in {:owner=>BeEF::Extension::Requester::RegisterPreHookCallback, :id=>18}.pre_hook_send()
[17:38:06][!] API Fire Error: Could not find table 'xssraysscans' in {:owner=>BeEF::Extension::Xssrays::RegisterPreHookCallback, :id=>20}.pre_hook_send()
..

That happen also with no ARE rules enabled. Just with a fresh BeEF installation.

**Comment by invokemethod** [comment] 2019-12-24 18:40
I can confirm the same behavior

**Comment by Comancheroo** [comment] 2019-12-29 11:12
I have the same problem

**Comment by invokemethod** [comment] 2019-12-29 16:14
the following commands resolved my issue.

rbenv install 2.5.3
rbenv global 2.5.3
ruby -v

output::

updating to ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

**Comment by laravelhelp2** [comment] 2019-12-31 06:56
With ruby 2.5.3 tables are created but ARE rules if enabled continue to don't work:

```
#<Thread:0x0000000003b50ee8@/tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:47 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	20: from /tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:48:in `block (2 levels) in <class:DynamicReconstruction>'
	19: from /tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `check_packets'
	18: from /tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `each'
	17: from /tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:80:in `block in check_packets'
	16: from /tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `execute'
	15: from /tmp/beef-0.5.0.0/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `new'
	14: from /tmp/beef-0.5.0.0/core/main/handlers/browserdetails.rb:19:in `initialize'
	13: from /tmp/beef-0.5.0.0/core/main/handlers/browserdetails.rb:513:in `setup'
	12: from /tmp/beef-0.5.0.0/core/main/autorun_engine/engine.rb:33:in `run'
	11: from /tmp/beef-0.5.0.0/core/main/autorun_engine/engine.rb:43:in `trigger'
	10: from /tmp/beef-0.5.0.0/core/main/autorun_engine/engine.rb:43:in `each'
	 9: from /tmp/beef-0.5.0.0/core/main/autorun_engine/engine.rb:88:in `block in trigger'
	 8: from /usr/share/rvm/gems/ruby-2.5.3/gems/activerecord-6.0.2.1/lib/active_record/inheritance.rb:70:in `new'
	 7: from /usr/share/rvm/gems/ruby-2.5.3/gems/activerecord-6.0.2.1/lib/active_record/inheritance.rb:70:in `new'
	 6: from /usr/share/rvm/gems/ruby-2.5.3/gems/activerecord-6.0.2.1/lib/active_record/core.rb:326:in `initialize'
	 5: from /usr/share/rvm/gems/ruby-2.5.3/gems/activemodel-6.0.2.1/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
	 4: from /usr/share/rvm/gems/ruby-2.5.3/gems/activerecord-6.0.2.1/lib/active_record/attribute_assignment.rb:22:in `_assign_attributes'
	 3: from /usr/share/rvm/gems/ruby-2.5.3/gems/activemodel-6.0.2.1/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
	 2: from /usr/share/rvm/gems/ruby-2.5.3/gems/activemodel-6.0.2.1/lib/active_model/attribute_assignment.rb:43:in `each'
	 1: from /usr/share/rvm/gems/ruby-2.5.3/gems/activemodel-6.0.2.1/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
/usr/share/rvm/gems/ruby-2.5.3/gems/activemodel-6.0.2.1/lib/active_model/attribute_assignment.rb:53:in `_assign_attribute': unknown attribute 'session' for BeEF::Core::Models::Execution. (ActiveModel::UnknownAttributeError)
```

**Comment by jcrew99** [comment] 2020-01-02 12:39
It seems to be with the activerecord tables, i have changed some of them so they can fit the convention more however some of the tables have callbacks that seem to be referenced improperly so it'll raise issues if they're changed, this itself issue should be resolved however its likely you will need to re-install Beef. Otherwise  just pass the -x tag when you start beef.  @laravelhelp2  sorry for the delay, Christmas took over a bit.

**Comment by jcrew99** [comment] 2020-01-31 04:33
@laravelhelp2  I am going to close this as the issue doesn't seem to be present anymore. Can you please try my comment above and if that doesnt work, re-open the ticket?

**Closed by jcrew99** 2020-01-31 04:33 UTC
