### ISSUE TITLE
IE 8 hook.js  JScript error

### ISSUE THREAD

**Issue by namivantoki** [beefproject/beef#1420] opened 2017-07-26 18:43 UTC
#### Environment

What version/revision of BeEF are you using?
Kali Linux latest, default settings
the latest version of BeEF 0.4.7.0

#### Summary
Hi, 
When I'm trying to hook an IE 8 nothing happens.
If I open the hook url directly from the browser gives me JScript compilation error.
Java installed on the system.
On the same system with FireFox works well.

#### Steps to Reproduce

Open hook url in IE 8 browser.

#### Additional Information

Screenshots attached with all information.

1. When I'm trying to open direct hook url for the 1st time
https://drive.google.com/open?id=0B139ALwUYRsScUM1MnMxS05oamc

2.  When I'm trying to open direct hook url for the 2nd time
https://drive.google.com/open?id=0B139ALwUYRsSVERmbjNXVGphbEU

3. Error when I trying to open
https://drive.google.com/open?id=0B139ALwUYRsSRFJYaFhNc2VDYW8

4. IE verison  
https://drive.google.com/open?id=0B139ALwUYRsSNnFNdG5OV21BWlU

5. Windows version
https://drive.google.com/open?id=0B139ALwUYRsSWmpfMVRRYkhrM1U

**Comment by bcoles** [comment] 2017-07-28 07:45
It looks like your browser is trying to download and execute the JS file with JScript, which is unusual, especially considering the file is served with a `Content-Type: text/javascript` header and no `Content-Disposition`.

I suspect you're using a non-standard configuration of Internet Explorer.

```
$ curl -isk http://127.0.0.1:3000/hook.js | head -n 12
HTTP/1.1 200 OK
Content-Type: text/javascript       # <--- text/javascript should not be downloaded.
Server: Apache/2.2.3 (CentOS)
Pragma: no-cache
Cache-Control: no-cache
Expires: 0
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET
Content-Length: 477851
Connection: keep-alive

/*! jQuery v1.12.4 | (c) jQuery Foundation | jquery.org/license */
```

**Comment by Center-Sun** [comment] 2017-12-21 08:08
It's work on my chrome and firefox,but when i try to hook IE,it request to get the hook.js and jquery-1.10.2.min.map,but the jquert not found. And it has a error: [SCRIPT1010: Expected identifier hook.js(8634,36)].

**Comment by bcoles** [comment] 2018-04-22 11:09
@namivantoki @Center-Sun @chicagoadmin 

I cannot reproduce this error.

Please ensure your BeEF is up to date. If the issue persists, please provide additional information.

**Comment by bcoles** [comment] 2018-04-22 11:12
I suspect you're encountering different issues.

I've tested a recent version of BeEF and can confirm support for IE8 is broken. This is presumably due to recent changes to jQuery.

**Comment by xssninja** [comment] 2018-05-31 06:31
Same error using IE on standard Metasploitable 3 VM. Even turning off ALL security settings it still produces the exact same error as quoted above including the line and character at which the error occurs.

**Comment by bcoles** [comment] 2018-05-31 09:20
IE8 does not support the latest version of jQuery.

BeEF should continue to support IE8. This will likely require either downgrading jQuery or implementing a saged hook.

Pull requests welcome.

**Comment by bcoles** [comment] 2018-06-11 05:04
As a stop-gap measure, I've rolled back the hook jQuery version to 1.12.4 to support IE6-8, until such time as staged hook functionality is implemented.

This should resolve the issue.

**Comment by bcoles** [comment] 2018-06-11 05:07
Closing this issue; tracking development of a staged hook in #1573

**Closed by bcoles** 2018-06-11 05:07 UTC
Labels: Defect, Priority Critical
