### ISSUE TITLE
[ARE] Invalid browser name error prevents auto rule execution (Chrome)

### ISSUE THREAD

**Issue by lean0x2F** [beefproject/beef#1304] opened 2016-09-27 19:40 UTC
Hi!

I'm having some issues with ARE rules on Chrome. Once the browser is hooked I see this error on the console:

`[15:59:36][!] [Browser Details] Invalid browser name returned from the hook browser's initial connection.`

Then nothing happens on the victim's browser. But if I manually trigger the ARE rule from the REST API, it works like a charm. 

I'm using the most vanilla rule, alert.json, and Chrome 53.0.2785.116 (64-bit, Linux)

Firefox, on the other hand, works as expected:

```
[15:59:37][*] New Hooked Browser [id:8, ip:127.0.0.1, browser:UNKNOWN-UNKNOWN, os:Linux-], hooked domain [Unknown:0]
[15:59:37][*] [ARE] Checking if any defined rules should be triggered on target.
[15:59:37]    |_  Browser version check -> (hook) UNKNOWN ALL (rule) : true
[15:59:37]    |_  OS version check -> (hook)  ALL (rule): true
[15:59:37]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[15:59:37]    |_  Found [1/1] ARE rules matching the hooked browser type/version.
[15:59:37]    |_  Preparing JS for command id [6], module [alert_dialog]
[15:59:37]    |_  Triggering ruleset [1] on HB 8
```

I think the "invalid browser name" error prevents ARE rules from loading. Is there a way to ignore this error?

Thank you!!!!

**Comment by lean0x2F** [comment] 2016-09-27 22:28
After a few hours, I found out what's happening. It has nothing to do with the browser name.

I lack enough ruby knowledge to understand this issue, but the root cause was this line:

```
beef/core/main/handlers/browserdetails.rb:212
if BeEF::Filters.is_valid_cookies?(cookies)
```

Execution ends here on Chrome, so ARE setup (which is at the bottom of that method) never gets done. "cookies" variable is nil (don't know really why), so I think is_valid_cookies() crashes somewhere because of that.

I came up with a very rudimentary solution to fix it while I wait for an official fix:

```          
          cookies = get_param(@data['results'], 'Cookies')
          if cookies.nil?
            BD.set(session_id, 'Cookies', "")
          else
            if BeEF::Filters.is_valid_cookies?(cookies)
              BD.set(session_id, 'Cookies', cookies)
            else
              self.err_msg "Invalid cookies returned from the hook browser's initial connection."
            end
          end
```

I hope this helps.

**Comment by antisnatchor** [comment] 2016-10-22 09:21
can you paste here the cookie value?
There might be a bug on is_valid_cookies method, but I doubt it.

Are you still getting this error @lean0x2F ?

**Comment by bcoles** [comment] 2017-04-23 03:21
Thanks @lean0x2F 

I've been able to reproduce this error.

You're correct that the `Invalid browser name returned from the hook browser's initial connection` error is unrelated. (See: #1343)

The error is caused by checking the length of a `nil` object during the length checking in `is_valid_cookies` resulting in ```undefined method `length' for nil:NilClass```

```ruby
  # Verify the cookies are valid
  # @param [String] str String for testing
  # @return [Boolean] If the string has valid cookie characters
  def self.is_valid_cookies?(str)
    return false if has_non_printable_char?(str)
    return false if str.length > 2000
    true
  end
```

For testing purposes, this issue can be reproduced by placing the following code as the first line in `def setup` in https://github.com/beefproject/beef/blob/master/core/main/handlers/browserdetails.rb

* `BeEF::Filters.is_valid_cookies?(nil)`

The above line will cause the hook and ARE to fail. Comparatively, using this line does not cause failure:

* `BeEF::Filters.is_valid_cookies?('')`

This highlights a larger underlying issue related to `nil` checking with all the filters which may or may not affect some other components of the `setup` method in the `BeEF::Core::Models::BrowserDetails` class.

This issue was due to a missing guard clause `return false unless is_non_empty_string?(str)` in some of the filters (the `is_non_empty_string` filter method contains a `nil` check guard clause). This has been added in commit 5c406b8d4f082770cbdf54aa08ae15c983d87bff.

I've also added a check to the `set` method in the BrowserDetails class to force `nil` to an empty string in commit 117091178f82576e7b63660469967b347e458826.

This issue should now be resolved. Closing.

**Closed by bcoles** 2017-04-23 03:21 UTC
Labels: Core, Defect

**Comment by lean0x2F** [comment] 2017-05-02 17:39
Thanks @bcoles!!!!
