### ISSUE TITLE
debug: false causing will exception on first request

### ISSUE THREAD

**Issue by wheatley** [beefproject/beef#2130] opened 2021-07-16 00:22 UTC
When making this configuration option true, when the first request i.e. to hit /ul/panel is made there is an exception.

## Environment

*Please identify the environment in which your issue occurred.*

1. latest clones 

2. 2.7.2

3. 

4. backend (ubuntu 20.04) frontend safari (Mac OS - Big Surr)

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
thin debugging

**Actual Behaviour:**
exception

## Steps to Reproduce

default clone from repo
set config value under http 
http
    debug: true
go to admin ui exception made

**Comment by bcoles** [comment] 2021-07-16 00:34
Dupe of #1856

```
E, [2021-07-15T20:33:02.940243 #143033] ERROR -- : Unexpected error while processing request: undefined method `each' for nil:NilClass
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/utils.rb:429:in `initialize'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/utils.rb:422:in `new'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/utils.rb:422:in `[]'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:39:in `call'
	/var/lib/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:253:in `call'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
	/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
	/root/Desktop/beef/core/main/server.rb:165:in `start'
	./beef:232:in `<main>'

```

**Closed** 2021-07-16 02:14 UTC
Labels: Defect, Priority Review, duplicate issue
