### ISSUE TITLE
pls help to fix this error 

### ISSUE THREAD

**Issue by dean-hacker** [beefproject/beef#2097] opened 2021-05-08 11:47 UTC
hi watch this vid https://www.youtube.com/watch?v=0s5OxXrbP3Y 
if you can help me ty i have discord Deanroks#1894 and i have anydesk led me know if you need the code to any desk

**Comment by bcoles** [comment] 2021-05-08 11:57
Closing as duplicate of #2095.

**Closed by bcoles** 2021-05-08 11:57 UTC
Labels: duplicate issue
