### ISSUE TITLE
Problem Webcam HTML5 and Spyder Eye

### ISSUE THREAD

**Issue by jesusprubio** [beefproject/beef#1070] opened 2014-11-17 20:24 UTC
Hi, everything seems to work fine but when I put the received data in a browser I can only see a minimal part of the capture in both cases (the top bar). The rest of modules seems to run without well, any idea please? :)

Tested on:
- Mac OS X Yosemite
- Chrome stable(38.0.2125.122) and Canary(41.0.2221.0 canary (64-bit))
- Beef from master
- Ruby from brew 1.9 (homebrew/versions/ruby193) and 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]

LOGS
[21:07:48][>] Event: 127.0.0.1 just joined the horde from the domain: 127.0.0.1:3000
[21:07:48][!] [Browser Details] Invalid browser name returned from the hook browser's initial connection.
[21:07:48][_] New Hooked Browser [id:1, ip:127.0.0.1, type:UNKNOWN-UNKNOWN, os:Macintosh], hooked domain [127.0.0.1:3000]
[21:07:48][>] WebSocket - Browser says helo! WebSocket is running
[21:07:48][>] WebSocket - activeSocket content [{"mf20FDRVB7q6QC7irpzi1i2ZSrLP6vqqinvjgA6Ww84MZKaU02LiQXaE0WJSIvBONWJxgErHZlhdnwIv"=>#<EventMachine::WebSocket::Connection:0x007fde27145de0 @signature=18, @options={:host=>"0.0.0.0", :port=>61985}, @debug=false, @secure=false, @tls_options={}, @data=nil, @onmessage=#Proc:0x007fde271445f8@/Users/baguira/Src/beef/core/main/network_stack/websocket/websocket.rb:170, @handler=#<EventMachine::WebSocket::Handler13:0x007fde259375c8 @request={"method"=>"GET", "path"=>"/", "query"=>{}, "host"=>#<Addressable::URI:0x3fef12c9becc URI:ws://127.0.0.1:61985>, "connection"=>"Upgrade", "pragma"=>"no-cache", "cache-control"=>"no-cache", "upgrade"=>"websocket", "origin"=>"http://127.0.0.1:3000", "sec-websocket-version"=>"13", "user-agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2221.0 Safari/537.36", "accept-encoding"=>"gzip, deflate, sdch", "accept-language"=>"es-ES,es;q=0.8,en;q=0.6", "cookie"=>"__utma=96992031.898199514.1403195396.1403195396.1403195396.1; __utmz=96992031.1403195396.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); FkMFa=3Ted8U7OZg6K2q6xIVtI7Rav63q82kUfgCrwBFTYSWBtLR2PLmtcsbEqzOD0ZOdTfR5raQ8JsixavopK; BEEFSESSION=e92fe073771e2385f4f5359d9f2e5ef534ac73f2b553481b575d8d4b92ee65321332ce705061af93293f0ad5d50e53118967d5e32f2b738d2393a2ef192e9e6a156830541f109c91267781d4d0a3d293; gpcVU=mf20FDRVB7q6QC7irpzi1i2ZSrLP6vqqinvjgA6Ww84MZKaU02LiQXaE0WJSIvBONWJxgErHZlhdnwIv", "sec-websocket-key"=>"lTGW+mhjpf7OzBUYvwxosA==", "sec-websocket-extensions"=>"permessage-deflate; client_max_window_bits"}, @connection=#<EventMachine::WebSocket::Connection:0x007fde27145de0 ...>, @debug=false, @state=:connected, @data="\x81\xDC\xFF-+\xA5\x84\x0FJ\xC9\x96[N\x87\xC5\x0FF\xC3\xCD\x1Dm\xE1\xAD{i\x92\x8E\ez\xE6\xC8DY\xD5\x85D\x1A\xCC\xCDwx\xD7\xB3}\x1D\xD3\x8E\B\xCB\x89GL\xE4\xC9z\\x9D\xCB`q\xEE\x9Ex\e\x97\xB3Dz\xFD\x9Eh\e\xF2\xB5~b\xD3\xBDbe\xF2\xB5UL\xE0\x8Deq\xC9\x97IE\xD2\xB6[\t\xD8", @application_data_buffer="">>}]
[21:07:57][>] Event: User with ip 127.0.0.1 has successfuly authenticated in the application.
[21:08:06][>] Server: mounted handler '/command/webcam_html5.js'
[21:08:06][>] Hard Load module: 'webcam_html5'
[21:08:09][>] [OBFUSCATION] Applying technique [scramble]
[21:08:09][>] [OBFUSCATION - SCRAMBLER] string [beef] scrambled -> [nru]
[21:08:09][>] [OBFUSCATION - SCRAMBLER] string [Beef] scrambled -> [XWW]
[21:08:09][>] [OBFUSCATION - SCRAMBLER] string [evercookie] scrambled -> [zbT]
[21:08:09][>] [OBFUSCATION - SCRAMBLER] string [BeEF] scrambled -> [Chz]
[21:08:09][>] [OBFUSCATION - SCRAMBLER] cookie [BEEFHOOK] scrambled -> [gpcVU]
[21:08:09][>] [OBFUSCATION] Applying technique [base_64]
[21:08:09][>] [OBFUSCATION - BASE64] Javascript has been base64'ed'
[21:08:09][*] Hooked browser [id:1, ip:127.0.0.1] has been sent instructions from command module [id:1, name:'Webcam HTML5']
[21:08:14][>] Event: Hooked browser [id:1, ip:127.0.0.1] has executed instructions from command module [id:1, name:'Webcam HTML5']
[21:08:14][_] Hooked browser [id:1, ip:127.0.0.1] has executed instructions from command module [id:1, name:'Webcam HTML5']

**Comment by bcoles** [comment] 2017-04-15 10:43
Hi @jesusprubio 

Did you get this working?

A few changes have been made to BeEF since your post which may have resolved this issue.

The Spyder Eye module will write out a PNG to `~/beef/`. Is the image also truncated?

**Comment by bcoles** [comment] 2017-04-16 18:02
Can't reproduce. Closing this issue.

**Closed by bcoles** 2017-04-16 18:02 UTC
Labels: Defect, Priority Review
