### ISSUE TITLE
eventmachine-1.0.9.1 incompatible library version

### ISSUE THREAD

**Issue by gearcapitan** [beefproject/beef#1503] opened 2018-02-09 23:58 UTC
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?
└─[$] <git:(master*)> ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
On what browser?
firefox
On what operating system?

kalilinux 2018.1 kde
#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

![kali linux-2018-02-09-17-58-31](https://user-images.githubusercontent.com/13740942/36055552-da45f1e8-0dc2-11e8-800a-fd3f2a38af22.png)

┌─[root@Gear] - [~/beef] - [vie feb 09, 17:58]
└─[$] <git:(master*)> ruby beef
/usr/local/rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:8:in `require': incompatible library version - /usr/local/rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so (LoadError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:8:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
        from /root/beef/core/loader.rb:10:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from beef:44:in `<main>'

**Comment by bcoles** [comment] 2018-02-17 08:47
That's unusual. I assisted someone get set up with BeEF from master branch on Kali 2018 the other day and didn't run into this issue.

Have you run `./install-beef` and `bundle install` ?

I'm downloading Kali 2018.1 now, but not sure when I'll get to take a look at it.

**Comment by bcoles** [comment] 2018-04-01 14:56
BeEF works fine for me on Kali Linux 2018.1 (Gnome).

Strange. A few users have had issues when using KDE systems. These issues aren't present when using Gnome. This shouldn't affect Ruby dependencies...

**Comment by bcoles** [comment] 2019-02-11 09:25
Closing this issue. I'm not sure if the underlying issue has been resolved, but Ruby 2.3 is EOL in ~30 days.

BeEF has been updated to exit if running on Ruby version `< 2.4`. The associated documentation has also been updated.

This issue is a year old now, so I'm kinda hoping that if it was an issue in an underlying lib that it's since been updated.

I'm download Parrot Security 4.5.1 now. If I can reproduce the issue on a fully up-to-date Parrot system, I'll reopen this issue.

**Closed by bcoles** 2019-02-11 09:25 UTC
Labels: Install
