### ISSUE TITLE
Autorun rules not working

### ISSUE THREAD

**Issue by pinkbat1** [beefproject/beef#1932] opened 2020-05-28 05:05 UTC
What version/revision of BeEF are you using?
0.5.0.0-alpha-pre

On what version of Ruby?
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]

On what browser?
Firefox 68.8.0esr (64-bit)

On what operating system?
Kali  Linux kali 5.5.0-kali1-amd64 #1 SMP Debian 5.5.13-2kali1 (2020-04-03) x86_64 GNU/Linux

#### Configuration

Are you using a non-default configuration?
No.

Have you enabled or disabled any BeEF extensions?
Yes. Evasion, metasploit

#### Summary
Trying to use autorun rules (sequential rules). I did a simple test copying the file fake_lasspass.json to the enabled directory, and when starting beef it says the rule was parsed successfully but when a new client is hooked it throws an exception. 

#### Expected Behaviour

What was the expected result?
Autorun rules should work. 

#### Actual Behaviour

#<Thread:0x000055d1a4d3cf68 /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:47 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	12: from /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:48:in `block (2 levels) in <class:DynamicReconstruction>'
	11: from /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `check_packets'
	10: from /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `each'
	 9: from /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:80:in `block in check_packets'
	 8: from /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `execute'
	 7: from /root/Documents/beef-master/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `new'
	 6: from /root/Documents/beef-master/core/main/handlers/browserdetails.rb:19:in `initialize'
	 5: from /root/Documents/beef-master/core/main/handlers/browserdetails.rb:513:in `setup'
	 4: from /root/Documents/beef-master/core/main/autorun_engine/engine.rb:33:in `run'
	 3: from /root/Documents/beef-master/core/main/autorun_engine/engine.rb:43:in `trigger'
	 2: from /root/Documents/beef-master/core/main/autorun_engine/engine.rb:43:in `each'
	 1: from /root/Documents/beef-master/core/main/autorun_engine/engine.rb:81:in `block in trigger'
/root/Documents/beef-master/core/main/autorun_engine/engine.rb:117:in `prepare_sequential_wrapper': undefined method `[]' for true:TrueClass (NoMethodError)

**Comment by jackdwalker** [comment] 2020-05-29 03:28
Hi @pinkbat1, thanks for raising the issue. You've got some decent detail here :)

Could you please show us the contents of your fake_lasspass.json?

**Comment by pinkbat1** [comment] 2020-05-29 06:29
I made a mistake it was actually confirm_close_tab.json. I tried a few different rules that come with beef, which I haven't modified. Here's confirm_close_tab.json:

{"name": "Confirm Close Tab",
  "author": "mgeeky",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [
    {"name": "confirm_close_tab",
      "condition": null,
      "code": null,
      "options": {
        "text":"Are you sure you want to navigate away from this page?",
        "usePopUnder":"true"
      }
    }
  ],
  "execution_order": [0],
  "execution_delay": [1000],
  "chain_mode": "sequential"
}

**Comment by pinkbat1** [comment] 2020-06-07 08:42
I got it working

**Comment by pinkbat1** [comment] 2020-06-07 09:40
Nvm actually I still have the same issue.

**Comment by jackdwalker** [comment] 2020-07-06 04:49
Hi @pinkbat1 - apologies for the delay. Real life has been busy :( 

I was able to reproduce your error, but I believe I've fixed this issue though. This issue was likely affecting other ARE rules from auto-loading as well.

During the Autorun execution process there was an issue with the `BeEF::Core::Models::Execution` object that was created. The function creating it was creating it with a `:rule_id` key (see lines 88 → 96 in `core/main/autorun_engine/engine.rb`). According to the `executions` object in the [Database Schema](https://github.com/beefproject/beef/wiki/Database-Schema#executions) page in the Wiki, this key should simply be called `:id`. This small change seemed to fix the problem!

Please pull the code in my [pull request](https://github.com/beefproject/beef/pull/1957) and let me know how you go. If my pull request has been merged by the time that you read this could you please `git pull origin master` and see if your problem has been fixed?

**Comment by jackdwalker** [comment] 2020-07-06 04:49
@bcoles - not sure how ARE was working with this issue. Execution objects should never have made it past creation.

**Comment by bcoles** [comment] 2020-07-06 05:16
> 
> 
> @bcoles - not sure how ARE was working with this issue. Execution objects should never have made it past creation.

I just tested the `alert.json` rule and it worked fine for me. I haven't reviewed the patch. I know the ARE rules were working (despite some bugs) prior to the migration to ActiveRecord. I haven't tested the ARE since the migration.

```
[ 1:15:07][*] New Hooked Browser [id:1, ip:172.16.191.165, browser:FF-68, os:Linux-], hooked domain [172.16.191.165:3000]
[ 1:15:07][*] [ARE] Checking if any defined rules should be triggered on target.
[ 1:15:07]    |_  Browser version check -> (hook) 68 ALL (rule) : true
[ 1:15:07]    |_  OS version check -> (hook)  ALL (rule): true
[ 1:15:07]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[ 1:15:07]    |_  Found [1/1] ARE rules matching the hooked browser type/version.
[ 1:15:07]    |_  Preparing JS for command id [1], module [alert_dialog]
[ 1:15:07]    |_  Triggering ruleset [1] on HB 1
[ 1:15:12][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: SUCCESS) from command module [cid:1, mod: 54, name:'Create Alert Dialog']
```

**Comment by bcoles** [comment] 2020-07-06 05:22
I also tested the `confirm_close_tab.json` JSON rule provided above, which also worked.

```
[ 1:18:28][*] [ARE] Checking if any defined rules should be triggered on target.
[ 1:18:28]    |_  Browser version check -> (hook) 68 ALL (rule) : true
[ 1:18:28]    |_  OS version check -> (hook)  ALL (rule): true
[ 1:18:28]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[ 1:18:28]    |_  Found [1/1] ARE rules matching the hooked browser type/version.
[ 1:18:28]    |_  Preparing JS for command id [1], module [confirm_close_tab]
[ 1:18:28]    |_  Triggering ruleset [1] on HB 1
[ 1:18:32][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: UNKNOWN) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
[ 1:18:33][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: UNKNOWN) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
[ 1:18:33][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: ERROR) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
[ 1:18:38][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: UNKNOWN) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
[ 1:18:38][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: ERROR) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
[ 1:18:44][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: UNKNOWN) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
[ 1:18:44][*] Hooked browser [id:1, ip:172.16.191.165] has executed instructions (status: ERROR) from command module [cid:1, mod: 102, name:'Confirm Close Tab']
```

I haven't looked at the code at all. If you're suggesting there's an issue with `rule_id` -> `id`, then maybe it works by accident due to a false assumption when rule_id = 1 and hb_id = 1 or something dumb like that.

**Comment by bcoles** [comment] 2020-07-06 05:28
> Have you enabled or disabled any BeEF extensions?
> Yes. Evasion, metasploit

The Evasion module does not play nicely with a lot of things. It was hacked on top and the rest of the code base has been updated piecemeal to support it. See related issue #1747. In particular https://github.com/beefproject/beef/issues/1747#issuecomment-515211649:

>
> Unfortunately the autorun rules engine does not work when base64 evasion is enabled.


I was able to produce a different (but probably related) error when enabling the evasion extension.

```
[ 1:23:58][*] New Hooked Browser [id:1, ip:172.16.191.165, browser:FF-68, os:Linux-], hooked domain [172.16.191.165:3000]
[ 1:23:58][*] [ARE] Checking if any defined rules should be triggered on target.
[ 1:23:58]    |_  Browser version check -> (hook) 68 ALL (rule) : true
[ 1:23:58]    |_  OS version check -> (hook)  ALL (rule): true
[ 1:23:58]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[ 1:23:58]    |_  Found [1/1] ARE rules matching the hooked browser type/version.
[ 1:23:59]    |_  Preparing JS for command id [1], module [confirm_close_tab]
[ 1:23:59][!] [ARE] Could not find module start index
[ 1:23:59][!] [ARE] Could not find module end index
[ 1:23:59][!] [ARE] There is likely a problem with the module's command.js parsing. Check Engine.clean_command_body
[ 1:23:59]    |_  Triggering ruleset [1] on HB 1
```

With debug output:

```
[ 1:25:34][>] Event: 172.16.191.165 appears to have come back online
[ 1:25:34]    |_  Browser version check -> (hook) 68 ALL (rule) : true
[ 1:25:34]    |_  OS version check -> (hook)  ALL (rule): true
[ 1:25:34]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[ 1:25:34]    |_  Found [1/1] ARE rules matching the hooked browser type/version.
[ 1:25:34][>] {"lastseen":"1594013134","ip":"172.16.191.165","id":1,"count":1,"session":"gk5z6NOhWlWbrsRqRcBd3QNevs2OYsyLPFkObLPDnQB7KcayhW1ZwuLT8jTYoEOJdm0Ox3KrdDySsBQE","firstseen":"1594013134","httpheaders":"{\"VERSION\":\"HTTP/1.1\",\"HOST\":\"172.16.191.165:3000\",\"USER_AGENT\":\"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0\",\"ACCEPT\":\"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01\",\"ACCEPT_LANGUAGE\":\"en-US,en;q=0.5\",\"ACCEPT_ENCODING\":\"gzip, deflate\",\"REFERER\":\"http://172.16.191.165:3000/demos/basic.html\",\"X_REQUESTED_WITH\":\"XMLHttpRequest\",\"CONNECTION\":\"keep-alive\",\"COOKIE\":\"BEEFHOOK=gk5z6NOhWlWbrsRqRcBd3QNevs2OYsyLPFkObLPDnQB7KcayhW1ZwuLT8jTYoEOJdm0Ox3KrdDySsBQE\"}","domain":"172.16.191.165","port":3000,"is_proxy":null}
[ 1:25:34][>] [Evasion] Applying technique: minify
[ 1:25:35][>] {"lastseen":"1594013135","ip":"172.16.191.165","count":2,"id":1,"session":"gk5z6NOhWlWbrsRqRcBd3QNevs2OYsyLPFkObLPDnQB7KcayhW1ZwuLT8jTYoEOJdm0Ox3KrdDySsBQE","firstseen":"1594013134","httpheaders":"{\"VERSION\":\"HTTP/1.1\",\"HOST\":\"172.16.191.165:3000\",\"USER_AGENT\":\"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0\",\"ACCEPT\":\"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01\",\"ACCEPT_LANGUAGE\":\"en-US,en;q=0.5\",\"ACCEPT_ENCODING\":\"gzip, deflate\",\"REFERER\":\"http://172.16.191.165:3000/demos/basic.html\",\"X_REQUESTED_WITH\":\"XMLHttpRequest\",\"CONNECTION\":\"keep-alive\",\"COOKIE\":\"BEEFHOOK=gk5z6NOhWlWbrsRqRcBd3QNevs2OYsyLPFkObLPDnQB7KcayhW1ZwuLT8jTYoEOJdm0Ox3KrdDySsBQE\"}","domain":"172.16.191.165","port":3000,"is_proxy":null}
[ 1:25:35][>] [OBFUSCATION - Minifier] JavaScript has been minified
[ 1:25:35][>] [Evasion] Applying technique: base_64
[ 1:25:35][>] [OBFUSCATION - Base64] Javascript has been base64 encoded
[ 1:25:35][>] [Evasion] Obfuscation completed (1846 bytes)
[ 1:25:35]    |_  Preparing JS for command id [1], module [confirm_close_tab]
[ 1:25:35][!] [ARE] Could not find module start index
[ 1:25:35][!] [ARE] Could not find module end index
[ 1:25:35][!] [ARE] There is likely a problem with the module's command.js parsing. Check Engine.clean_command_body
[ 1:25:35]    |   Final Modules Wrapper:
[ 1:25:35]    |    
[ 1:25:35]    |                   var confirm_close_tab_82c42e6b54 = function(){
[ 1:25:35]    |                       true
[ 1:25:35]    |                   };
[ 1:25:35]    |                   var confirm_close_tab_82c42e6b54_can_exec = false;
[ 1:25:35]    |                   var confirm_close_tab_82c42e6b54_mod_output = null;
[ 1:25:35]    |               
[ 1:25:35]    |_   setTimeout(function(){confirm_close_tab_82c42e6b54();}, 1000); 
[ 1:25:35]    |_  Triggering ruleset [1] on HB 1
```

**Comment by jackdwalker** [comment] 2020-07-06 07:32
@bcoles - are you happy for this issue to be closed when the PR addressing the initial error is merged? The evasion related issue can probably be tackled with issue #1747, would you agree?

**Comment by bcoles** [comment] 2020-07-06 07:41
> @bcoles - are you happy for this issue to be closed when the PR addressing the initial error is merged?

Sure, if your patch fixes this issue (when Evasion is disabled).

> The evasion related issue can probably be tackled with #1747, would you agree? 

Yes, #1747 should be used to track the Evasion + ARE issue.

> If so I'll copy across your error and it can be addressed within that issue.

No need. The error is already documented in that issue.

**Closed** 2020-07-09 00:27 UTC
Labels: Autorun Rules Engine, Defect
