### ISSUE TITLE
Beef panel is not showing Online browsers but that particular hooked browser is showing in both zombie and logs

### ISSUE THREAD

**Issue by yapandy82** [beefproject/beef#2521] opened 2022-07-30 10:36 UTC
![image](https://user-images.githubusercontent.com/63541597/181906547-4a0ba3ba-014f-4c08-b461-b980f7d66d53.png)
please help asap,
thanks.

**Comment by bcoles** [comment] 2022-07-30 16:56
The Logs tabs shows logs. The Zombies tabs show zombies.

If no browsers are listed under 'Online Browsers' then no browsers are online.

**Comment by yapandy82** [comment] 2022-07-31 04:32
But I hooked 2 browsers and they still weren't under the 'Online Browsers' tab though they were added to the Logs.

**Comment by bcoles** [comment] 2022-07-31 04:46
Are there any errors in the web browser console?

Also BeEF version 0.5.0.0. is old now. Version 0.5.4.0 is the latest release.

**Comment by yapandy82** [comment] 2022-07-31 04:49
Shall I update it and try again? There are similar issues on GitHub and the fix was to fix the country_code which i couldn't understand

**Comment by bcoles** [comment] 2022-07-31 04:58
> There are similar issues on GitHub and the fix was to fix the country_code which i couldn't understand

There's insufficient information in this issue to understand the root cause.

The country code issue was patched over a year ago and is patched in the latest version.


> Shall I update it and try again? 

Yes.

**Comment by yapandy82** [comment] 2022-07-31 05:02
May you please tell how to update Beef?

**Comment by bcoles** [comment] 2022-07-31 05:07
> May you please tell how to update Beef?

That depends how you installed it.

If you're using BeEF from GitHub, you can simply `git pull`.

**Comment by yapandy82** [comment] 2022-07-31 05:11
I installed linux from Zsecurity, Beef was already in it

**Comment by bcoles** [comment] 2022-07-31 05:15
> I installed linux from Zsecurity, Beef was already in it

I don't know what that means. BeEF may be installed as operating system package, in which it should update when you update packages.


Or you can download the release zip file. Or you can clone from GitHub.

**Comment by yapandy82** [comment] 2022-07-31 05:24
![image](https://user-images.githubusercontent.com/63541597/182011508-6b093482-5d2a-43b2-9105-72e59c410b5d.png)

**Comment by bcoles** [comment] 2022-07-31 05:29
`bundle install` has to be run from within the BeEF directory. It installs the dependencies listed in the Gemfile. The Gemfile is loaded from the working directory.

**Comment by yapandy82** [comment] 2022-07-31 05:36
![image](https://user-images.githubusercontent.com/63541597/182011847-22225baa-c5cf-4eb6-b95a-8aed27b1ef7a.png)

**Comment by bcoles** [comment] 2022-07-31 05:51
You're using Ruby 2.5. Support for Ruby 2.5 ended over a year ago on 2021-04-05.

I have no idea what ZSecurity is - but it seems to be very out of date. Have you updated system packages recently?

**Comment by yapandy82** [comment] 2022-07-31 06:03
![image](https://user-images.githubusercontent.com/63541597/182012521-cbece803-11de-4dc7-bf04-c350674d2a50.png
reinstalling beef but what is up with this error?

**Comment by yapandy82** [comment] 2022-07-31 06:03
![image](https://user-images.githubusercontent.com/63541597/182012537-9380e97f-ca32-48ce-86f5-bc518bd3f936.png)
Now im using official linux and installing beef,but getting this error

**Comment by bcoles** [comment] 2022-07-31 06:07
> Now im using official linux and installing beef,but getting this error

It looks like your packages are broken for some reason.

You shouldn't need to use the installer. Clone from the repo, run `bundle install`. You might need some operating system packages, in which case you will need to fix your packages.

Refer to the installation guide.

* https://github.com/beefproject/beef/blob/master/INSTALL.txt
* https://github.com/beefproject/beef/wiki/Installation

**Comment by bcoles** [comment] 2022-07-31 06:08
There is not enough information to reproduce the issue. Update BeEF. Closing this issue.

**Closed by bcoles** 2022-07-31 06:08 UTC
Labels: Question, Need more information

**Comment by yapandy82** [comment] 2022-07-31 06:27
![image](https://user-images.githubusercontent.com/63541597/182013178-d21077c2-9c0d-4122-8259-4b6eb55b045e.png)
![image](https://user-images.githubusercontent.com/63541597/182013190-fbde1a45-b32b-4f11-8d7d-be2886d0314f.png)

**Comment by bcoles** [comment] 2022-07-31 06:32
The sqlite issue is easily fixed. The xmlrpc issue is not so easy.

```
apt-get install libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev
```

**Comment by yapandy82** [comment] 2022-07-31 06:36
![image](https://user-images.githubusercontent.com/63541597/182013418-4787e8fe-c366-42ec-80ac-432c63b0aba2.png)

**Comment by bcoles** [comment] 2022-07-31 06:42
SQLite package are required. They should be available in Kali. Try these:

```
libsqlite3-0 - SQLite 3 shared library
libsqlite3-dev - SQLite 3 development files
libxslt1-dev - XSLT 1.0 processing library - development kit
libxslt1.1 - XSLT 1.0 processing library - runtime library
```

You may need to update packages first. `apt-get update`.
