### ISSUE TITLE
Denied permision in beEF

### ISSUE THREAD

**Issue by ATO99Y** [beefproject/beef#3105] opened 2024-06-29 04:48 UTC
Its not working for me it says this always i runned it and others got it to, this is the permision denied error:

/home/userland/beef/core/main/console/banners.rb:55:in `ip_address_list': Permission denied - getifaddrs (Errno::EACCES)
        from /home/userland/beef/core/main/console/banners.rb:55:in `print_network_interfaces_count'
        from ./beef:244:in `<main>
        
Idk about this im testing this for my self i am a advance at linux this is unexpected for me and outhers.

I tested on
ubuntu and Kali linux

**Comment by bcoles** [comment] 2024-06-29 04:59
> /home/userland

It looks like you're using [UserLAnd](https://userland.tech/) on Android? If so, this is a dupe of #2443.

**Comment by ATO99Y** [comment] 2024-06-29 05:19
Yes im using userland kinda embarrassing😅

**Closed** 2024-06-29 10:52 UTC
