### ISSUE TITLE
Console is not defined (hook.js line 2238)

### ISSUE THREAD

**Issue by badbob** [beefproject/beef#1130] opened 2015-07-02 10:56 UTC
Trying to run hook.js in Java application with embeded Firefox 3.6.*.
Possible should to define console manually if not defined?

**Comment by antisnatchor** [comment] 2015-08-04 14:29
Interesting. can you tell me exactly which lines are the problem?
Maybe some modules? Or are you use client_debug: true maybe?

Or, we have some console object somewhere, which I doubt as would prevent IE6 hooking and so on.
Let me know

**Comment by bcoles** [comment] 2015-08-04 15:02
The use of `console.log` is forbidden within the framework.

Instead, `beef.debug` should be used, which wraps `console.log` if it exists.

Using `client_debug: true` will allow debug messages in console. However, setting this value to true or false should make no difference to the error you're encountering.

Unfortunately the line number in the JavaScript you've provided is not of much help as the hook.js file is generated dynamically.

Can you try `git pull` ? Your issue may be resolved in the latest version.

There were several instances of `console.log` which were removed in the month of July:
* fa2f1754001ecc31695fb634e5dd7e51ea32aba1
* 1f00c396c6df876e078b412f33693208aeab4e26
* aaefde9b43fe010d89df4f383155d2499b67ff49

For what it's worth, it's possible that the issue is being caused by a third-party library, for example the jQuery Migrate library makes use of `console.log`.

* core/main/client/lib/jquery-migrate-1.2.1.min.js

**Comment by badbob** [comment] 2015-08-05 06:50
Can't reproduce in HEAD revision. 
Looks like, issue was fixed in July al bcoles said.

**Comment by bcoles** [comment] 2015-08-05 17:45
Closed. Thanks @badbob

**Closed by bcoles** 2015-08-05 17:45 UTC
